config/routes.rb
Rails.application.routes.draw do
  get :reload, to: 'home#reload', defaults: { format: :json }
  get :welcome, to: 'home#welcome'

  root 'home#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
  # protect_from_forgery prepend: true
  prepend_view_path Rails.root.join('frontend')
end

app/controllers/concerns/serialized.rb
module Serialized
  extend ActiveSupport::Concern

  def render_json(item, root_name = controller_name.singularize)
    ApplicationController.render file: "components/#{controller_name}/_#{root_name}",
                                 locals: { "#{root_name}": item }, layout: false
    # if item.errors.any?
    #   render_errors(item)
    # else
    #   render_html = ApplicationController.render file: "components/#{controller_name}/_#{root_name}",
    #                                              locals: { "#{root_name}": item }, layout: false
    #   render_json_message
    # end
  end

  def render_json_message
    render json: { message: t('.message') }
  end

  def render_errors(object)
    render plain: object.errors.full_messages.join('<br/>'), status: :forbidden
  end

  def render_not_found
    render status: :not_found
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :folder, :load_files

  def welcome; end

  def reload
    render json: { data: @files }
  end

  private

  def folder
    @folder = params[:folder].nil? ? '/public' : params[:folder]
  end

  def load_files
    @files = DropboxClient.new(@folder).list_folder
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_flash
    javascript_tag('App.flash = JSON.parse(' "'#{j({ success: flash.notice, error: flash.alert }.to_json)}'" ');')
  end

  def app_name
    Rails.application.class.parent_name.underscore.humanize.split.map(&:capitalize).join(' ')
  end

  def full_title(page_title)
    base_title = app_name
    if page_title.empty?
      base_title
    else
      "#{base_title} #{page_title}"
    end
  end

  def component(component_name, locals = {}, &block)
    folder = component_name.split('_').first
    name = component_name.split('_').last
    render("components/#{folder}/#{name}", locals, &block)
  end

  alias c component
end

app/views/home/welcome.slim
.container-fluid
.container-fluid
  .row
    .col-xs-2
      ul.list-unstyled
        li
          a.btn.js-dingle href="javascript:void(0);"  = t('action')
        li
          a.btn.js-dingle href="javascript:void(0);" = t('action')
        li
          a.btn.js-dingle href="javascript:void(0);" = t('action')
        li
          a.btn.js-dingle href="javascript:void(0);" = t('action')
    .col-xs-8
      #files
    .col-xs-2
      a.btn.btn-primary.js-dingle href="javascript:void(0);" = t('action')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'vendor', media: 'all' %>
  </head>
  <body>
    <div id="main">
      <%=	render 'shared/header' %>
      <div class="container">
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
    <%= javascript_pack_tag 'application'%>
    <%=	render_flash %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header"></div>
    <ul class="nav navbar-nav">
      <li>
        <%=	link_to  t('title'), reload_path(folder: '/Public'), remote: true, class: 'js-reload' %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_title.html.erb
<%- provide(:title, title) %>
<h1><%= yield(:title) %></h1>